export const ADD_FRIEND = 'ADD_FRIEND'
export const GET_FRIEND = 'GET_FRIEND'

export const USER_LOGIN = 'USER_LOGIN'
export const LOGGED_USER = 'LOGGED_USER'
export const USER_LOGOUT = 'USER_LOGOUT'
export const SET_USER_TYPE = 'SET_USER_TYPE'
export const PREPARE_USER_REGISTRATION = 'PREPARE_USER_REGISTRATION'
export const SET_USER_PROFILE = 'SET_USER_PROFILE'

export const LOADING = 'LOADING'
export const CLEAR_LOADING = 'CLEAR_LOADING'
export const ERROR_NOTIFICATION = 'ERROR_NOTIFICATION'
export const SUCCESS_NOTIFICATION = 'SUCCESSNOTIFICATION'

export const GET_STUDENT = 'GET_STUDENT'
