export const ADD_FRIEND = 'ADD_FRIEND'
export const GET_FRIEND = 'GET_FRIEND'

export const USER_LOGIN = 'USER_LOGIN'
export const LOGGED_USER = 'LOGGED_USER'
export const USER_LOGOUT = 'USER_LOGOUT'
export const SET_USER_TYPE = 'SET_USER_TYPE'
export const PREPARE_USER_REGISTRATION = 'PREPARE_USER_REGISTRATION'

export const REGISTRATION_LOADING = 'REGISTRATION_LOADING'
export const CLEAR_REGISTRATION_LOADING = 'CLEAR_REGISTRATION_LOADING'
export const REGISTRATION_ERROR_NOTIFICATION = 'REGISTRATION_ERROR_NOTIFICATION'
export const REGISTRATION_SUCCESS_NOTIFICATION = 'REGISTRATION_SUCCESSNOTIFICATION'
